import type { Bookmark } from './types';

export const mockBookmarks: Bookmark[] = [
  {
    id: '1',
    url: 'https://vercel.com',
    title: 'Vercel: Develop. Preview. Ship.',
    description: 'Vercel is the platform for frontend developers, providing the speed and reliability innovators need to create at the moment of inspiration.',
    tags: ['development', 'hosting', 'frontend'],
    favicon: 'https://assets.vercel.com/image/upload/front/favicon/vercel/favicon.ico',
    createdAt: '2024-05-20T10:00:00Z',
  },
  {
    id: '2',
    url: 'https://tailwindcss.com',
    title: 'Tailwind CSS - Rapidly build modern websites without ever leaving your HTML.',
    description: 'A utility-first CSS framework packed with classes that can be composed to build any design, directly in your markup.',
    tags: ['css', 'frontend', 'design'],
    favicon: 'https://tailwindcss.com/favicons/favicon-32x32.png?v=3',
    createdAt: '2024-05-19T14:30:00Z',
  },
  {
    id: '3',
    url: 'https://github.com',
    title: 'GitHub: Where the world builds software',
    description: 'GitHub is where over 100 million developers shape the future of software, together. Contribute to the open source community, manage your Git repositories, review code like a pro, track bugs and features, power your CI/CD and DevOps workflows, and secure software before it ships.',
    tags: ['development', 'git', 'collaboration'],
    favicon: 'https://github.githubassets.com/favicons/favicon.svg',
    createdAt: '2024-05-18T09:15:00Z',
  },
  {
    id: '4',
    url: 'https://figma.com',
    title: 'Figma: The Collaborative Interface Design Tool.',
    description: 'Figma is a vector graphics editor and prototyping tool which is primarily web-based, with additional offline features enabled by desktop applications for macOS and Windows.',
    tags: ['design', 'ui', 'ux', 'collaboration'],
    favicon: 'https://static.figma.com/app/icon/1/favicon.png',
    createdAt: '2024-05-21T11:00:00Z',
  },
  {
    id: '5',
    url: 'https://notion.so',
    title: 'Notion – The all-in-one workspace for your notes, tasks, wikis, and databases.',
    description: 'Notion is an application that provides components such as notes, databases, kanban boards, wikis, calendars and reminders. Users can connect these components to create their own systems for knowledge management, note taking, data management, project management, among others.',
    tags: ['productivity', 'tools', 'organization'],
    favicon: 'https://www.notion.so/images/favicon.ico',
    createdAt: '2024-05-17T18:00:00Z',
  },
   {
    id: '6',
    url: 'https://www.smashingmagazine.com/',
    title: 'Smashing Magazine — For Web Designers And Developers',
    description: 'Smashing Magazine is a website and eBook publisher that offers editorial content and professional resources for web developers and web designers.',
    tags: ['articles', 'webdev', 'design'],
    favicon: 'https://www.smashingmagazine.com/images/favicon/favicon.svg',
    createdAt: '2024-05-22T09:00:00Z',
  },
  {
    id: '7',
    url: 'https://dribbble.com/',
    title: 'Dribbble - Discover the World’s Top Designers & Creative Professionals',
    description: 'Dribbble is the leading destination to find & showcase creative work and home to the world\'s best design professionals.',
    tags: ['design', 'inspiration', 'portfolio'],
    favicon: 'https://cdn.dribbble.com/assets/favicon-63b290442c6c67c215701d6d676f4b2af55dc383430a6724e42c8d2a13cbe4c1.ico',
    createdAt: '2024-05-22T10:30:00Z',
  },
];
